### ISSUE TITLE
Collection type for item has wrong key

### ISSUE THREAD

**Issue by MelanX** [FooterManDev/heracles-jetbrains#1]
Maybe in an older version, this was correct, but on 1.20.1, it is just `collection`.
Plugin version: 1.0.2

![image](https://github.com/FooterManDev/heracles-jetbrains/assets/26039509/18a7cb62-c754-462b-a442-eff57a05e4e3)

**Comment by FooterManDev** [comment]
This will be updated in the new version of the Schema
